version: '2'
services:
    courses_alpha_qs-app:
        image: courses_alpha_qs
        external_links:
            - courses_alpha_qs-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/courses_alpha_qs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    courses_alpha_qs-mysql:
        extends:
            file: mysql.yml
            service: courses_alpha_qs-mysql
