version: '2'
services:
    courses_alpha_qs-mysql:
        container_name: courses_alpha_qs-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/Courses_Alpha_QS/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=courses_alpha_qs
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
